// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIHSr9-_EfBJR8GudvzWjPKO-oYSG6IkM',
    appId: '1:132518173573:web:578cb5d0e984fb3c0042ec',
    messagingSenderId: '132518173573',
    projectId: 'gluco-guard-tutor',
    authDomain: 'gluco-guard-tutor.firebaseapp.com',
    storageBucket: 'gluco-guard-tutor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMnH6tEMnxMeFsZROvF4d2JbmdLC_HfDQ',
    appId: '1:32535166517:android:aac44a93e0efed18ef7b7c',
    messagingSenderId: '32535166517',
    projectId: 'glycplus',
    storageBucket: 'glycplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRuyfU4PEFc1EcsoZHvlyzD0T6F_kzoqE',
    appId: '1:132518173573:ios:64968662aa58902e0042ec',
    messagingSenderId: '132518173573',
    projectId: 'gluco-guard-tutor',
    storageBucket: 'gluco-guard-tutor.firebasestorage.app',
    iosBundleId: 'Y',
  );
}